version: 2.1

jobs:
  py36_mac:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: "Installing Conda"
          command: |
            curl -o Miniconda3-latest-MacOSX-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
            bash ./Miniconda3-latest-MacOSX-x86_64.sh -b
      - run:
          name: "Testing VizSeq"
          no_output_timeout: 60m
          command: |
            ~/miniconda3/bin/pip install -e ~/project
            ~/miniconda3/bin/python -m tests.test_all

  py37_mac:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: "Installing Conda"
          command: |
            curl -o Miniconda3-latest-MacOSX-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
            bash ./Miniconda3-latest-MacOSX-x86_64.sh -b
            ~/miniconda3/bin/conda init bash
      - run:
          name: "Testing VizSeq"
          no_output_timeout: 60m
          command: |
            ~/miniconda3/bin/conda create -n vizseq37 python=3.7 -q -y
            ~/miniconda3/bin/conda run -n vizseq37 pip install -e ~/project
            ~/miniconda3/bin/conda run -n vizseq37 python -m tests.test_all

  py36_linux:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo apt-get install -y expect
      - run: python -m tests.test_all

  py37_linux:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo apt-get install -y expect
      - run: python -m tests.test_all

  py36_win:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Installing Conda
          command: |
            choco install miniconda3 -y --version=4.6.14
            C:\tools\miniconda3\Scripts\conda.exe init powershell
      - run:
          name: Preparing conda environment
          command: |
            conda create -n vizseq python=3.6 -q -y
      - run:
          name: Testing vizseq
          command: |
            $env:PYTHONIOENCODING="utf_8"
            conda activate vizseq
            python3 -m tests.test_all
            exit $LASTEXITCODE

  py37_win:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Installing Conda
          command: |
            choco install miniconda3 -y --version=4.6.14
            C:\tools\miniconda3\Scripts\conda.exe init powershell
      - run:
          name: Preparing conda environment
          command: |
            conda create -n vizseq  python=3.7 -q -y
      - run:
          name: Testing VizSeq
          command: |
            $env:PYTHONIOENCODING="utf_8"
            conda activate vizseq
            python3 -m tests.test_all
            exit $LASTEXITCODE

workflows:
  version: 2
  build:
    jobs:
      - py36_linux
      - py37_linux
      - py36_mac
      - py37_mac
      - py36_win
      - py37_win

orbs:
  win: circleci/windows@1.0.0
